# Generated by Django 3.0.8 on 2020-07-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_search_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coderepository',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
