# Generated by Django 3.0.5 on 2020-05-29 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_search_app', '0002_codedocumentvisitlog_querylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeDocumentQueryRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('rating', models.IntegerField()),
                ('rater_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_search_app.CodeDocument')),
            ],
        ),
    ]
