LANGUAGES = ['python']
LANGUAGES_NUM_FILES = {
    'python': 14,
    'ruby': 2,
}

EMBEDDING_SIZE = 128

CODE_VOCABULARY_SIZE = 10000
CODE_TOKEN_COUNT_THRESHOLD = 10
CODE_MAX_SEQ_LENGTH = 200

DOCSTRING_VOCABULARY_SIZE = 10000
DOCSTRING_TOKEN_COUNT_THRESHOLD = 10
DOCSTRING_MAX_SEQ_LENGTH = 30
